### ISSUE TITLE
Java 8 issue with Android

### ISSUE THREAD

**Issue by eugene-galkine** [dustin-johnson/timezonemap#2]
Tried calling `TimeZoneMap.forRegion` on an Android tablet running 6.0.1 and it crashed with the following error:

```
java.lang.NoSuchMethodError: No virtual method lines()Ljava/util/stream/Stream; in class Ljava/io/BufferedReader; or its super classes (declaration of 'java.io.BufferedReader' appears in /system/framework/core-libart.jar)
        at us.dustinj.timezonemap.utils.Properties.getProperties(Properties.java:17)
        at us.dustinj.timezonemap.data.DataLocator.getProperties(DataLocator.java:34)
        at us.dustinj.timezonemap.data.DataLocator.getMapArchiveFilename(DataLocator.java:26)
        at us.dustinj.timezonemap.data.DataLocator.getDataInputStream(DataLocator.java:19)
        at us.dustinj.timezonemap.TimeZoneMap.forRegion(TimeZoneMap.java:92)
```

**Comment by eugene-galkine** [comment]
I have fixed this issue and opened a pull request

**Comment by dustin-johnson** [comment]
@eugene-galkine, sorry for the delay. I agree that it is poor form that this library doesn't support older version of Android very well. I would very much like to keep the clean syntax that Java 8's streams provided, however, so I opted to migrate this library to Kotlin. With Kotlin we can use sequences, which are very much like streams but don't require an update to the JVM or JDK to work, thus they are compatible with older versions of Android. I've made the needed changes, tested them all the way back to Android 19 (KitKat 4.4, released in 2013). The newest release (4.0, since it breaks API compatibility slightly by removing Optional) has been created and should be live in Maven central in a couple hours.

Please let me know if this works for your use case, and thank you for pushing me to more carefully consider older Android releases.

**Comment by eugene-galkine** [comment]
@dustin-johnson Version 4.0 is working on the devices I needed it on. Thank you.

**Comment by dustin-johnson** [comment]
Great! Thanks for getting back to me.
